[versions]
kotlin = "2.3.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
gradle-shadow = { id = "com.gradleup.shadow", version = "9.3.0" }

[libraries]
# Core Language Library
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

# Function Library
koin-core-jvm = { module = "io.insert-koin:koin-core-jvm", version = "4.1.0" }
koin-annotations-jvm = { module = "io.insert-koin:koin-annotations-jvm", version = "2.3.1" }